### ISSUE TITLE
java.lang.NoSuchMethodError: 'byte[] dan200.computercraft.core.terminal.Palette.getRenderColours(int)'

### ISSUE THREAD

**Issue by 2A5F** [dfdyz/VoidPowerMod#2]
```
java.lang.NoSuchMethodError: 'byte[] dan200.computercraft.core.terminal.Palette.getRenderColours(int)'
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderUtils.drawString(ScreenRenderUtils.java:42) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderUtils.drawTerminalForeground(ScreenRenderUtils.java:59) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderer.lambda$renderTerminal$1(ScreenRenderer.java:163) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderer.renderToBuffer(ScreenRenderer.java:380) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderer.renderTerminal(ScreenRenderer.java:162) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderer.renderSafe(ScreenRenderer.java:115) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.dfdyz.void_power.client.renderer.tileentities.glass_screen.ScreenRenderer.renderSafe(ScreenRenderer.java:38) ~[void_power-1.2.1.jar%23521!/:1.2.1] {re:classloading}
	at com.simibubi.create.foundation.blockEntity.renderer.SafeBlockEntityRenderer.m_6922_(SafeBlockEntityRenderer.java:20) ~[create-1.20.1-0.5.1.h.jar%23476!/:0.5.1.h] {re:classloading,re:mixin}
	at net.minecraft.client.renderer.blockentity.BlockEntityRenderDispatcher.m_112284_(BlockEntityRenderDispatcher.java:90) ~[client-1.20.1-20230612.114412-srg.jar%23606!/:?] 
```

**Comment by dfdyz** [comment]
computer craft version?

**Comment by 2A5F** [comment]
cc-tweaked-1.20.1-forge-1.113.1

**Comment by dfdyz** [comment]
please use cc-1.111.x

**Comment by dfdyz** [comment]
new version will be compated in future update

**Comment by Yeetmaster982** [comment]
I received the same error using cc-tweaked-1.20.1-forge-1.111.0

**Comment by Yeetmaster982** [comment]
I got the same error while using cc-tweaked-1.20.1-forge-1.111.0

**Comment by dfdyz** [comment]
new version is use 1.113.x
